package com.aiswatchdog.models;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Represents an alert generated by a detector.
 */
public class Alert implements Serializable {
    private static final long serialVersionUID = 1L;

    public enum AlertType {
        GEOFENCE_VIOLATION,
        DARK_EVENT,
        RENDEZVOUS,
        FISHING_IN_MPA,
        SANCTIONS_MATCH,
        AIS_SPOOFING,
        CABLE_PROXIMITY
    }

    public enum Severity {
        LOW,
        MEDIUM,
        HIGH,
        CRITICAL
    }

    @JsonProperty("alert_id")
    private String alertId;

    @JsonProperty("alert_type")
    private AlertType alertType;

    private Severity severity;
    private String mmsi;

    @JsonProperty("vessel_name")
    private String vesselName;

    @JsonProperty("imo_number")
    private String imoNumber;

    @JsonProperty("flag_state")
    private String flagState;

    private double latitude;
    private double longitude;

    @JsonProperty("detected_at")
    private String detectedAt;

    private String title;
    private String description;

    // Additional context specific to alert type
    private Map<String, Object> details;

    // Default constructor
    public Alert() {
        this.alertId = UUID.randomUUID().toString();
        this.detectedAt = Instant.now().toString();
        this.details = new HashMap<>();
    }

    // Builder-style constructor
    public Alert(AlertType alertType, Severity severity, String mmsi) {
        this();
        this.alertType = alertType;
        this.severity = severity;
        this.mmsi = mmsi;
    }

    // Static factory methods for common alerts
    public static Alert geofenceViolation(AISPosition position, String zoneName, String zoneType) {
        Alert alert = new Alert(AlertType.GEOFENCE_VIOLATION, Severity.HIGH, position.getMmsi());
        alert.setVesselName(position.getShipName());
        alert.setImoNumber(position.getImoNumber());
        alert.setLatitude(position.getLatitude());
        alert.setLongitude(position.getLongitude());
        alert.setTitle("Geofence Violation: " + zoneName);
        alert.setDescription(String.format(
                "Vessel %s (MMSI: %s) entered %s zone: %s",
                position.getShipName() != null ? position.getShipName() : "Unknown",
                position.getMmsi(),
                zoneType,
                zoneName
        ));
        alert.addDetail("zone_name", zoneName);
        alert.addDetail("zone_type", zoneType);
        alert.addDetail("vessel_speed", position.getSpeedOverGround());
        alert.addDetail("vessel_course", position.getCourseOverGround());

        // Adjust severity based on zone type
        if ("sanctioned_waters".equals(zoneType)) {
            alert.setSeverity(Severity.CRITICAL);
        } else if ("MPA".equals(zoneType) && position.isFishingVessel()) {
            alert.setSeverity(Severity.CRITICAL);
        }

        return alert;
    }

    public static Alert darkEvent(VesselState lastState, long gapMinutes) {
        Severity severity;
        if (gapMinutes > 24 * 60) {
            severity = Severity.HIGH;
        } else if (gapMinutes > 6 * 60) {
            severity = Severity.MEDIUM;
        } else {
            severity = Severity.LOW;
        }

        Alert alert = new Alert(AlertType.DARK_EVENT, severity, lastState.getMmsi());
        alert.setVesselName(lastState.getShipName());
        alert.setImoNumber(lastState.getImoNumber());
        alert.setLatitude(lastState.getLastLatitude());
        alert.setLongitude(lastState.getLastLongitude());
        alert.setTitle("Vessel Gone Dark");
        alert.setDescription(String.format(
                "Vessel %s (MMSI: %s) has not transmitted for %d hours %d minutes. Last position: %.4f, %.4f",
                lastState.getShipName() != null ? lastState.getShipName() : "Unknown",
                lastState.getMmsi(),
                gapMinutes / 60,
                gapMinutes % 60,
                lastState.getLastLatitude(),
                lastState.getLastLongitude()
        ));
        alert.addDetail("gap_minutes", gapMinutes);
        alert.addDetail("last_speed", lastState.getLastSpeed());
        alert.addDetail("last_seen", lastState.getLastSeen());

        return alert;
    }

    public static Alert rendezvous(AISPosition vessel1, AISPosition vessel2,
                                    double distance, long durationMinutes) {
        Alert alert = new Alert(AlertType.RENDEZVOUS, Severity.MEDIUM, vessel1.getMmsi());
        alert.setVesselName(vessel1.getShipName());
        alert.setImoNumber(vessel1.getImoNumber());
        alert.setLatitude(vessel1.getLatitude());
        alert.setLongitude(vessel1.getLongitude());
        alert.setTitle("Potential Ship-to-Ship Transfer");
        alert.setDescription(String.format(
                "Vessels %s and %s within %.0fm for %d minutes at open sea",
                vessel1.getShipName() != null ? vessel1.getShipName() : vessel1.getMmsi(),
                vessel2.getShipName() != null ? vessel2.getShipName() : vessel2.getMmsi(),
                distance,
                durationMinutes
        ));
        alert.addDetail("vessel2_mmsi", vessel2.getMmsi());
        alert.addDetail("vessel2_name", vessel2.getShipName());
        alert.addDetail("distance_meters", distance);
        alert.addDetail("duration_minutes", durationMinutes);
        alert.addDetail("vessel1_type", vessel1.getShipType());
        alert.addDetail("vessel2_type", vessel2.getShipType());

        // Increase severity if tanker involved
        if (vessel1.isTanker() || vessel2.isTanker()) {
            alert.setSeverity(Severity.HIGH);
        }

        return alert;
    }

    public static Alert sanctionsMatch(AISPosition position, String sanctionSource,
                                        String sanctionReason) {
        Alert alert = new Alert(AlertType.SANCTIONS_MATCH, Severity.CRITICAL, position.getMmsi());
        alert.setVesselName(position.getShipName());
        alert.setImoNumber(position.getImoNumber());
        alert.setLatitude(position.getLatitude());
        alert.setLongitude(position.getLongitude());
        alert.setTitle("Sanctioned Vessel Detected");
        alert.setDescription(String.format(
                "Vessel %s (MMSI: %s) matches %s sanctions list. Reason: %s",
                position.getShipName() != null ? position.getShipName() : "Unknown",
                position.getMmsi(),
                sanctionSource,
                sanctionReason
        ));
        alert.addDetail("sanction_source", sanctionSource);
        alert.addDetail("sanction_reason", sanctionReason);

        return alert;
    }

    public static Alert cableProximity(AISPosition position, String zoneName,
                                       Severity severity, String title,
                                       String description, Map<String, Object> details) {
        Alert alert = new Alert(AlertType.CABLE_PROXIMITY, severity, position.getMmsi());
        alert.setVesselName(position.getShipName());
        alert.setImoNumber(position.getImoNumber());
        alert.setLatitude(position.getLatitude());
        alert.setLongitude(position.getLongitude());
        alert.setTitle(title);
        alert.setDescription(description);
        if (details != null) {
            for (Map.Entry<String, Object> entry : details.entrySet()) {
                alert.addDetail(entry.getKey(), entry.getValue());
            }
        }
        return alert;
    }

    // Getters and Setters
    public String getAlertId() {
        return alertId;
    }

    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }

    public AlertType getAlertType() {
        return alertType;
    }

    public void setAlertType(AlertType alertType) {
        this.alertType = alertType;
    }

    public Severity getSeverity() {
        return severity;
    }

    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    public String getMmsi() {
        return mmsi;
    }

    public void setMmsi(String mmsi) {
        this.mmsi = mmsi;
    }

    public String getVesselName() {
        return vesselName;
    }

    public void setVesselName(String vesselName) {
        this.vesselName = vesselName;
    }

    public String getImoNumber() {
        return imoNumber;
    }

    public void setImoNumber(String imoNumber) {
        this.imoNumber = imoNumber;
    }

    public String getFlagState() {
        return flagState;
    }

    public void setFlagState(String flagState) {
        this.flagState = flagState;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public String getDetectedAt() {
        return detectedAt;
    }

    public void setDetectedAt(String detectedAt) {
        this.detectedAt = detectedAt;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Map<String, Object> getDetails() {
        return details;
    }

    public void setDetails(Map<String, Object> details) {
        this.details = details;
    }

    public void addDetail(String key, Object value) {
        if (this.details == null) {
            this.details = new HashMap<>();
        }
        this.details.put(key, value);
    }

    @Override
    public String toString() {
        return "Alert{" +
                "alertId='" + alertId + '\'' +
                ", alertType=" + alertType +
                ", severity=" + severity +
                ", mmsi='" + mmsi + '\'' +
                ", title='" + title + '\'' +
                '}';
    }
}
