#!/usr/bin/env python3
"""
Create all required Kafka topics for AIS Guardian on Aiven.

Run this script after creating a new Aiven Kafka service to set up all required topics.

Usage:
    python scripts/setup_kafka_topics.py

Required topics:
    - ais-raw: Raw AIS position data from ingestion
    - alerts: Anomaly alerts from Flink detectors
    - reference-data: Geofences and reference data for detectors
    - sanctions: Sanctioned vessels and high-risk flags for shadow fleet detection
    - ais-enriched: Enriched AIS positions from Flink
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from confluent_kafka.admin import AdminClient, NewTopic

# Load environment
env_path = Path(__file__).parent.parent / '.env'
load_dotenv(env_path)

# Kafka configuration
bootstrap_servers = os.getenv('KAFKA_BOOTSTRAP_SERVERS')
ssl_ca = os.getenv('KAFKA_SSL_CA_CERT', './ca.pem')
ssl_cert = os.getenv('KAFKA_SSL_CERT', './service.cert')
ssl_key = os.getenv('KAFKA_SSL_KEY', './service.key')

# Resolve paths relative to project root
project_root = Path(__file__).parent.parent
ssl_ca = str(project_root / ssl_ca.lstrip('./'))
ssl_cert = str(project_root / ssl_cert.lstrip('./'))
ssl_key = str(project_root / ssl_key.lstrip('./'))

print(f"Connecting to: {bootstrap_servers}")

# Create admin client
admin_config = {
    'bootstrap.servers': bootstrap_servers,
    'security.protocol': 'SSL',
    'ssl.ca.location': ssl_ca,
    'ssl.certificate.location': ssl_cert,
    'ssl.key.location': ssl_key,
}

admin = AdminClient(admin_config)

# Required topics (free tier: max 2 partitions per topic)
REQUIRED_TOPICS = [
    ('ais-raw', 1, 'Raw AIS position data from AISStream ingestion'),
    ('alerts', 1, 'Anomaly alerts generated by Flink detectors'),
    ('reference-data', 1, 'Geofences and reference data for detectors'),
    ('sanctions', 1, 'Sanctioned vessels and high-risk flags for shadow fleet detection'),
    ('ais-enriched', 1, 'Enriched AIS positions from Flink processing'),
]

def main():
    # Get existing topics
    metadata = admin.list_topics(timeout=10)
    existing = set(t for t in metadata.topics if not t.startswith('_'))

    print(f"\nExisting topics: {sorted(existing)}")
    print("\nCreating missing topics...")

    topics_to_create = []
    for topic_name, partitions, description in REQUIRED_TOPICS:
        if topic_name in existing:
            print(f"  ✓ {topic_name} - already exists")
        else:
            topics_to_create.append(NewTopic(topic_name, num_partitions=partitions, replication_factor=2))
            print(f"  → {topic_name} - will create ({description})")

    if topics_to_create:
        print("\nCreating topics...")
        fs = admin.create_topics(topics_to_create)

        for topic, f in fs.items():
            try:
                f.result()
                print(f"  ✓ Created: {topic}")
            except Exception as e:
                if 'TOPIC_ALREADY_EXISTS' in str(e):
                    print(f"  ✓ Already exists: {topic}")
                else:
                    print(f"  ✗ Failed to create {topic}: {e}")

    # Final verification
    print("\n" + "="*50)
    metadata = admin.list_topics(timeout=10)
    final_topics = sorted(t for t in metadata.topics if not t.startswith('_'))
    print("Final topic list:")
    for t in final_topics:
        print(f"  - {t}")

    # Check all required topics exist
    missing = set(t[0] for t in REQUIRED_TOPICS) - set(final_topics)
    if missing:
        print(f"\n⚠ WARNING: Missing topics: {missing}")
        return 1
    else:
        print("\n✓ All required topics are ready!")
        return 0


if __name__ == '__main__':
    exit(main())
