# Ververica Secrets Configuration Template
#
# These secrets need to be created in Ververica Cloud before deploying.
# You can create them via the Ververica UI or using the vvp CLI.

---
# Secret 1: Kafka connection credentials
apiVersion: v1
kind: Secret
metadata:
  name: aiven-kafka-credentials
  namespace: default  # Change to your namespace
spec:
  data:
    # Base64 encoded values - replace with your actual Aiven Kafka details
    # To encode: echo -n "your-value" | base64
    bootstrap-servers: "YOUR_BASE64_ENCODED_BOOTSTRAP_SERVERS"
    # Example: echo -n "kafka-xxx.aivencloud.com:28739" | base64

    truststore-password: "YOUR_BASE64_ENCODED_TRUSTSTORE_PASSWORD"
    # Example: echo -n "changeit" | base64 -> Y2hhbmdlaXQ=

    keystore-password: "YOUR_BASE64_ENCODED_KEYSTORE_PASSWORD"
    # Example: echo -n "changeit" | base64 -> Y2hhbmdlaXQ=

---
# Secret 2: Kafka SSL certificates (binary files)
#
# For SSL certificates, you need to:
# 1. Convert Aiven PEM certificates to JKS/PKCS12 format (see scripts/setup-ssl.sh)
# 2. Upload the binary files to Ververica as a secret
#
# Using Ververica UI:
# 1. Go to Secrets in your namespace
# 2. Create a new secret named "aiven-kafka-ssl-certs"
# 3. Add two files:
#    - truststore.jks (from setup-ssl.sh output)
#    - keystore.p12 (from setup-ssl.sh output)
#
# Using vvp CLI:
# vvp secret create aiven-kafka-ssl-certs \
#   --from-file=truststore.jks=./truststore.jks \
#   --from-file=keystore.p12=./keystore.p12 \
#   --namespace default

---
# Alternative: Using Ververica's built-in secret management via UI
#
# 1. Log into Ververica Cloud Console
# 2. Navigate to your namespace → Secrets
# 3. Click "Create Secret"
# 4. For "aiven-kafka-credentials":
#    - Type: Key-Value
#    - Add keys: bootstrap-servers, truststore-password, keystore-password
# 5. For "aiven-kafka-ssl-certs":
#    - Type: Files
#    - Upload: truststore.jks, keystore.p12
